name: Update Weather

permissions:
  contents: write

on:
  schedule:
    - cron: "0 * * * *"  # ทุก 1 ชั่วโมง
  workflow_dispatch:

jobs:
  fetch-weather:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install axios dotenv

      - name: Fetch weather data
        run: node scripts/fetch-weather.js
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git add weather.json
          git commit -m "Update weather data [auto]" || echo "No changes"
          git push origin HEAD:${{ github.ref_name }}
